name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Cache Gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle

    - name: Build with Gradle
      run: ./gradlew build
