name: Android CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # android emulator runs faster on macos
    # ref: https://github.com/ReactiveCircus/android-emulator-runner#usage
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.17.0
        with:
          api-level: 23
          target: google_apis
          script: ./ciRunTests.sh

      - name: publish screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: espresso_screenshots
          path: espresso_screenshots
