name: Android CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.17.0
        with:
          api-level: 23
          target: google_apis
          script: ./ciRunTests.sh