name: Android CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    # android emulator runs faster on macos
    # ref: https://github.com/ReactiveCircus/android-emulator-runner#usage
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 28 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          target: google_apis
          arch: x86_64
          cores: 4
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./ciRunTests.sh

      - name: publish screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: espresso_screenshots_${{ matrix.api-level }}
          path: espresso_screenshots

      - name: upload results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation-test-results ${{ matrix.api-level }}
          path: ./**/build/reports/androidTests/connected/**
